version: "3.8"
services:
  backend:
    image: $IMAGE_TAG
    container_name: container-blog-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDTIME: ${BUILDTIME}
        VERSION: ${VERSION}
        REVISION: ${REVISION}
    # ports:
    #   - "${PORT}:${PORT}"
    # env_file:
    #   - .env

# networks:
#   nginx_network:
#     external: true