version: "3.8"
services:
  backend:
    image: $IMAGE_TAG
    container_name: container-blog-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_LABELS=${DOCKER_LABELS}
        - DOCKER_METADATA=${DOCKER_METADATA}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

# networks:
#   nginx_network:
#     external: true