version: "3.8"
services:
  backend:
    image: $IMAGE_NAME
    container_name: container-blog-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_NAME: ${IMAGE_NAME}
        LABELS: ${LABELS}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

# networks:
#   nginx_network:
#     external: true


