version: "3.8"
services:
  backend:
    image: $IMAGE_TAG
    container_name: container-blog-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDTIME: ${BUILDTIME}
        VERSION: ${VERSION}
        REVISION: ${REVISION}